# Generated by Django 4.0.1 on 2022-03-16 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_petphoto_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
